class CategoryScreenModal {
  final String? id,
      images,
      Name,
      cashondelevery,
      productdeliveryin,
      freeshipping,
      quantity,
      regularprice,
      offer,
      description;

  CategoryScreenModal(
      {this.id,
      this.images,
      this.Name,
      this.cashondelevery,
      this.productdeliveryin,
      this.freeshipping,
      this.quantity,
      this.regularprice,
      this.offer,
      this.description});
}

List demoRecentFiles = [
  CategoryScreenModal(
      id: "121",
      images: "assets/icons/xd_file.svg",
      Name: "XD File",
      cashondelevery: "false",
      productdeliveryin: "20",
      freeshipping: "true",
      quantity: "10",
      regularprice: "20",
      offer: "0",
      description: "Apples from limpopo"),
  CategoryScreenModal(
      id: "121",
      images: "assets/icons/xd_file.svg",
      Name: "XD File",
      cashondelevery: "false",
      productdeliveryin: "20",
      freeshipping: "true",
      quantity: "10",
      regularprice: "20",
      offer: "0",
      description: "Apples from limpopo"),
  CategoryScreenModal(
      id: "121",
      images: "assets/icons/xd_file.svg",
      Name: "XD File",
      cashondelevery: "false",
      productdeliveryin: "20",
      freeshipping: "true",
      quantity: "10",
      regularprice: "20",
      offer: "0",
      description: "Apples from limpopo"),
  CategoryScreenModal(
      id: "121",
      images: "assets/icons/xd_file.svg",
      Name: "XD File",
      cashondelevery: "false",
      productdeliveryin: "20",
      freeshipping: "true",
      quantity: "10",
      regularprice: "20",
      offer: "0",
      description: "Apples from limpopo"),
  CategoryScreenModal(
      id: "121",
      images: "assets/icons/xd_file.svg",
      Name: "XD File",
      cashondelevery: "false",
      productdeliveryin: "20",
      freeshipping: "true",
      quantity: "10",
      regularprice: "20",
      offer: "0",
      description: "Apples from limpopo"),
  CategoryScreenModal(
      id: "121",
      images: "assets/icons/xd_file.svg",
      Name: "XD File",
      cashondelevery: "false",
      productdeliveryin: "20",
      freeshipping: "true",
      quantity: "10",
      regularprice: "20",
      offer: "0",
      description: "Apples from limpopo"),
  CategoryScreenModal(
      id: "121",
      images: "assets/icons/xd_file.svg",
      Name: "XD File",
      cashondelevery: "false",
      productdeliveryin: "20",
      freeshipping: "true",
      quantity: "10",
      regularprice: "20",
      offer: "0",
      description: "Apples from limpopo"),
  CategoryScreenModal(
      id: "121",
      images: "assets/icons/xd_file.svg",
      Name: "XD File",
      cashondelevery: "false",
      productdeliveryin: "20",
      freeshipping: "true",
      quantity: "10",
      regularprice: "20",
      offer: "0",
      description: "Apples from limpopo"),
  CategoryScreenModal(
      id: "121",
      images: "assets/icons/xd_file.svg",
      Name: "XD File",
      cashondelevery: "false",
      productdeliveryin: "20",
      freeshipping: "true",
      quantity: "10",
      regularprice: "20",
      offer: "0",
      description: "Apples from limpopo"),
  CategoryScreenModal(
      id: "121",
      images: "assets/icons/xd_file.svg",
      Name: "XD File",
      cashondelevery: "false",
      productdeliveryin: "20",
      freeshipping: "true",
      quantity: "10",
      regularprice: "20",
      offer: "0",
      description: "Apples from limpopo"),
];
